---
- name: 'Create Consul service definition'
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ nimbus_portal_client_consul_service_file_name }}'
    consul_services:
      - id:   '{{ nimbus_portal_client_service_name }}'
        name: '{{ nimbus_portal_client_consul_service_name }}'
        port: '{{ nimbus_portal_client_listening_port }}'
        address: '{{ nimbus_portal_client_public_address }}'
        tags: ['{{ env }}.{{ stage }}', 'eth1', 'nimbus']
        checks:
          - id:       '{{ nimbus_portal_client_consul_service_name }}-health'
            name:     '{{ nimbus_portal_client_consul_service_name }}-health'
            interval: '{{ nimbus_portal_client_consul_check_interval }}'
            timeout:  '{{ nimbus_portal_client_consul_check_timeout }}'
            disabled: '{{ nimbus_portal_client_consul_check_disabled }}'
            script:   '{{ nimbus_portal_client_rpc_script_path }} discv5_nodeInfo'
            type:     'script'
            success_before_passing:   '{{ nimbus_portal_client_consul_success_before_passing }}'
            failures_before_warning:  '{{ nimbus_portal_client_consul_failures_before_warning }}'
            failures_before_critical: '{{ nimbus_portal_client_consul_failures_before_critical }}'

      - id:   '{{ nimbus_portal_client_service_name }}-metrics'
        name: '{{ nimbus_portal_client_consul_metrics_service_name }}'
        port: '{{ nimbus_portal_client_metrics_port }}'
        address: '{{ ansible_local.wireguard.vpn_ip }}'
        tags: ['{{ env }}.{{ stage }}', 'eth1', 'nimbus', 'metrics']
        meta:
          container: '{{ nimbus_portal_client_service_name }}'
        checks:
          - id:       '{{ nimbus_portal_client_service_name }}-metrics-health'
            name:     '{{ nimbus_portal_client_consul_metrics_service_name }}-health'
            interval: '{{ nimbus_portal_client_consul_check_interval }}'
            timeout:  '{{ nimbus_portal_client_consul_check_timeout }}'
            disabled: '{{ nimbus_portal_client_consul_check_disabled }}'
            http:     'http://localhost:{{ nimbus_portal_client_metrics_port }}/health'
            type:     'http'
            success_before_passing:   '{{ nimbus_portal_client_consul_success_before_passing }}'
            failures_before_warning:  '{{ nimbus_portal_client_consul_failures_before_warning }}'
            failures_before_critical: '{{ nimbus_portal_client_consul_failures_before_critical }}'
