---
- include_tasks: checks.yml
- when: not nimbus_portal_client_ansible_disabled
  block:
    - include_tasks: install.yml
    - include_tasks: user.yml
    - include_tasks: config.yml
    - include_tasks: build.yml
    - include_tasks: service.yml
    - include_tasks: consul.yml
